# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: chickenmasala
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: tests
# "service" is the name of this project. This will also be added to your AWS resource names.
service: law-copilot-rem

stages:
  default:
    params:
      tableName: sessions-table-${sls:stage}
  stg:
    params:
      NODE_ENV: staging
  prod:
    params:
      NODE_ENV: production

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-plugin-common-excludes

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.12
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [SessionsTable, Arn]
  environment:
    NODE_ENV: ${param:NODE_ENV}
    TABLE_NAME: ${param:tableName}
    MISTRAL-API-KEY: ${ssm:api/law-copilot/mistral-api-key}
    MODEL_NAME: open-mixtral-8x22b

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 30
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    SessionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${param:tableName}
